name: Create Merged Jira Release Card

on:
  push:
    branches:
      - develop

jobs:
  create-release-card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - name: Fetch master branches
        run : git fetch origin master:master

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install requests PyYAML

      - name: Run script to create Jira card
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/merged_release_card.py